# OBS! Glöm inte köra filen: kubectl apply -f deployment.yaml
# Denna fil innehåller både deployment- och service.yaml, går att separera med --- sträck
# Kör dessa kommando i ordning:
# minikube start
# kubectl apply -f deploymentall.yaml
# kubectl get pods -l app=frontend
# kubectl get deployments
# minikube service 

# Deployment och Service för frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vedmastaren/frontend:v1.0.0  
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend

# Deployment och Service för user
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: vedmastaren/user:v1.0.0 
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
  - port: 4001
    targetPort: 4001
  selector:
    app: user

# Deployment och Service för todo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: vedmastaren/todo:v1.0.0 
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: todo

# Deployment och Service för MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

