# Skriv detta i terminalen:
# docker-compose up -d 

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - group-project-network

  todoservice:
    build:
      context: ./DevOps1BE-todo
      dockerfile: Dockerfile
    container_name: container_todo
    ports:
      - "4000:4000"
    networks:
      - group-project-network

  userservice:
    build:
      context: ./DevOps1BE-user
      dockerfile: Dockerfile
    container_name: container_user
    ports:
      - "4001:4001"
    networks:
      - group-project-network
  
  frontend:
    build:
      context: ./DevOps1FE
      dockerfile: Dockerfile
    container_name: container_frontend
    ports:
      - "80:80"
    networks:
      - group-project-network

networks:
  group-project-network:
    name: group-project-network
    driver: bridge